[2025-07-04T17:49:21.761+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T17:49:21.821+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_model_retraining.retrain_model manual__2025-07-04T17:49:18.237995+00:00 [queued]>
[2025-07-04T17:49:21.835+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_model_retraining.retrain_model manual__2025-07-04T17:49:18.237995+00:00 [queued]>
[2025-07-04T17:49:21.835+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-04T17:49:21.849+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): retrain_model> on 2025-07-04 17:49:18.237995+00:00
[2025-07-04T17:49:21.868+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=501) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-04T17:49:21.877+0000] {standard_task_runner.py:63} INFO - Started process 512 to run task
[2025-07-04T17:49:21.871+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weekly_model_retraining', 'retrain_model', 'manual__2025-07-04T17:49:18.237995+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/retraining_dag.py', '--cfg-path', '/tmp/tmpahw1rgo9']
[2025-07-04T17:49:21.889+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask retrain_model
[2025-07-04T17:49:21.934+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T17:49:22.018+0000] {task_command.py:426} INFO - Running <TaskInstance: weekly_model_retraining.retrain_model manual__2025-07-04T17:49:18.237995+00:00 [running]> on host 1f9ae480a8ef
[2025-07-04T17:49:22.222+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rajat' AIRFLOW_CTX_DAG_ID='weekly_model_retraining' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T17:49:18.237995+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-04T17:49:18.237995+00:00'
[2025-07-04T17:49:22.224+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T17:49:22.278+0000] {logging_mixin.py:188} INFO - [INFO] Found latest timestamp: 2025-07-03-15
[2025-07-04T17:49:22.279+0000] {logging_mixin.py:188} INFO - [INFO] Starting model training...
[2025-07-04T17:49:22.527+0000] {logging_mixin.py:188} WARNING - 2025/07/04 17:49:22 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-07-04T17:49:24.060+0000] {logging_mixin.py:188} INFO -          actor  anomaly_score  anomaly
0   0-kodiya-0       0.285104    False
1  00-10-01-11       0.285104    False
2   001ryu-ryu       0.268308    False
3       0047ol       0.156115    False
4      004Ajay       0.285104    False
[2025-07-04T17:49:24.065+0000] {logging_mixin.py:188} INFO - [INFO] Training completed successfully.
[2025-07-04T17:49:24.066+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-04T17:49:24.067+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T17:49:24.076+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weekly_model_retraining, task_id=retrain_model, run_id=manual__2025-07-04T17:49:18.237995+00:00, execution_date=20250704T174918, start_date=20250704T174921, end_date=20250704T174924
[2025-07-04T17:49:24.129+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-04T17:49:24.161+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T17:49:24.169+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
